// <auto-generated />
namespace Contratos_vers_beta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifieddatimeanull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifieddatimeanull));
        
        string IMigrationMetadata.Id
        {
            get { return "201810262245131_modifieddatimeanull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
